name: inp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - pillow
  - scipy
  - pyqt
  - matplotlib
  - opencv
  - scikit-learn
  - ipywidgets
  - pip
  - pip:
    - opencv-python-headless
